###
POST http://localhost:3000/user/signin
Content-Type: application/json

{
    "email": "abc@test.com",
    "password": "123"
}

###
POST http://localhost:3000/peep
Content-Type: application/json

{
    "content": "this is my first peep"
}

###
GET http://localhost:3000/peep
Content-Type: application/json
