POST http://localhost:3000/signup
Content-Type: application/json

{
    "email": "abc@test.com",
    "password": "123",
    "nickname": "hi"
}

###
POST http://localhost:3000/signin
Content-Type: application/json

{
    "email": "a",
    "password": "1"
}

###
GET http://localhost:3000/user/follower
Content-Type: application/json
